name: hd_wallet
description: HD Wallet implementation with BIP32 and BIP39 support
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  crypto: 3.0.5
  convert: 3.1.1
  pointycastle: 3.9.1
  secp256k1_flutter_wrapper:
    path: ../secp256k1_flutter_wrapper
  
dev_dependencies:
  lints: 5.0.0
  test: 1.25.0

