name: secp256k1_flutter_wrapper
description: FFI wrapper for Bitcoin secp256k1 library
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  ffi: 2.1.3
  
dev_dependencies:
  lints: 5.0.0

